- hosts: all
  gather_facts: no

  tasks:
    - name: Stop services
      community.docker.docker_compose:
        # link the docker compose file in the docker folder
        project_src: "{{ dest_files }}"
        build: false
        stopped: true
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output

  # handlers:
  #   - name: restart nginx
  #     ansible.builtin.service:
  #       name: nginx
  #       state: reloaded
  #     become: yes
