database_host: "{{ vault_database_host }}"
database_name: "{{ vault_database_name }}"
database_username: "{{ vault_database_username }}"
database_password: "{{ vault_database_password }}"
database_port: "{{ vault_database_port }}"
