version: "3.9"

services:
  redmine:
    image: redmine:alpine3.18
    restart: always
    environment:
      REDMINE_DB_POSTGRES: "{{ vars.DATABASE_HOST }}"
      REDMINE_DB_PORT: "{{ vars.DATABASE_PORT }}"
      REDMINE_DB_DATABASE: "{{ vars.DATABASE_NAME }}"
      REDMINE_DB_USERNAME: "{{ vars.DATABASE_USERNAME }}"
      REDMINE_DB_PASSWORD: "{{ vars.DATABASE_PASSWORD }}"

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - redmine
