version: "3.9"

services:
  redmine:
    image: redmine:alpine3.18
    restart: unless-stopped
    environment:
      REDMINE_DB_POSTGRES: "{{ database_host }}"
      REDMINE_DB_PORT: "{{ database_port }}"
      REDMINE_DB_DATABASE: "{{ database_name }}"
      REDMINE_DB_USERNAME: "{{ database_username }}"
      REDMINE_DB_PASSWORD: "{{ database_password }}"

    ports:
      - 80:3000
